### ISSUE TITLE
Missing changelog for older versions of @swc/cli

### ISSUE THREAD

**Issue by evenfrost** [swc-project/pkgs#22]
Where to find the changelog for `@swc/cli` `v0.3.5` and older?

I've just upgraded the package from `v0.1.x` to `0.3.9` and it stopped compiling the project, and I would like to know what caused the issues.

**Comment by evenfrost** [comment]
Yeah, I found it out as well, but it would be good to have a changelog with all the breaking changes, at least.

**Comment by dzienisz** [comment]
I am also interested in this changelog.

**Comment by dzienisz** [comment]
0.3.5 
  0.3.4 
  0.3.3 
  0.3.2 
  0.3.1 
  0.3.0 
  0.2.3 
  0.2.2 
  0.2.1 
  0.2.0 
  0.1.65 
  0.1.64 

this could help updating

**Comment by frankpengau** [comment]
Sent PR to backfill the changes and keep track till `0.1.60` - coinciding with the start of 2023 commits in the old repo.

PR: https://github.com/swc-project/pkgs/pull/62

Hopefully this helps out others to not go through the same struggles as me trying to back test again all the versions until the version in my `package.json` file.
