### ISSUE TITLE
`npx swc src -d build` outputs files into `build/src` instead of `build`

### ISSUE THREAD

**Issue by 3axap4eHko** [swc-project/pkgs#28]
When using `npx swc` to compile and output files from the `src` directory to the `build` directory using the command `npx swc src -d build`, the output is incorrectly placed into `build/src` instead of directly into `build`. This behavior is unexpected and diverges from the documentation (or expected behavior) where the output should directly be in the `build` directory.

**Comment by kdy1** [comment]
See --strip-leading-paths

**Comment by 3axap4eHko** [comment]
@kdy1 is there anything similar for `swcx`?
