### ISSUE TITLE
@swc/cli version 0.3.0 has older compiled code

### ISSUE THREAD

**Issue by devdannym** [swc-project/pkgs#33]
I was trying to leverage the new `--cli-config-file` option in version 0.3.0 when I kept seeing this error:

`error: unknown option '--cli-config-file'`

After reviewing the published package for 0.3.0,  I discovered that the changes are in the src folder, but the compiled lib folder has no changes made for that version.

**Comment by kdy1** [comment]
Use 0.3.10
