### ISSUE TITLE
`TypeError: require(...).getOptions is not a function` ==> missing `loader-utils` in peer deps

### ISSUE THREAD

**Issue by stevebeauge** [swc-project/pkgs#38]
Hello,

When using webpack 4 `swc-loader` relies on `loader-utils` to work https://github.com/swc-project/pkgs/blob/f035da2969b45ab9b1810fc2b93be9798ccf8069/packages/swc-loader/src/index.js#L12

However, this package is not listed in the dependencies explicitly. It may work when using `npm`, because it's a [phantom dependency](https://rushjs.io/pages/advanced/phantom_deps/) (installed by webpack in the flat node_modules), but when using `pnpm`, it fails because the dependency is not found with:

    TypeError: require(...).getOptions is not a function

I believe you should declare `loader-utils` as a peer dependency to ensure the package is available.

As a workaround, `pnpm` allows tweaking the dependencies of dependencies using [`pnpm.packageExtension`](https://pnpm.io/package_json#pnpmpackageextensions) field. I was able to get rid of this error using in my package.json file :

```json
{
    "pnpm": {
        "packageExtensions": {
            "swc-loader": {
                "peerDependencies": {
                    "loader-utils": ">=1.2.3"
                }
            }
        }
    }
}
```

**Comment by kdy1** [comment]
It's not a peer dependency for users using webpack 5, so you should install it by yourself.

**Comment by stevebeauge** [comment]
@kdy1 : installing in my project `loader-utils` won't work.

The pnpm symlink structure requires to have every dependency known.

If the dependency is optional, you may set [`peerdependenciesmeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta):

```json
{
  "peerDependencies": {
     "loader-utils": ">=1.2.3"
  },
  "peerDependenciesMeta": {
    "loader-utils": {
      "optional": true
    }
  }
}
```

This way, wp5 users won't be required to install the dependency, but it will be available to wp4 users (at least theorically, I never played with such edge case).

If you need a repro I can take a few minutes to create it.

**Comment by stevebeauge** [comment]
I'm trying to create a minimal repro but in this repro, I don't get the error.

Let me close the issue while I investigate if there's interference with other tools. I'll reopen the issue only if I get a proper repro.
