### ISSUE TITLE
Error Please, make sure to install them as development dependencies.

### ISSUE THREAD

**Issue by realtrynna** [swc-project/pkgs#63]
Hello, I am running NestJS as PM2 on **ubuntu version 24.04.1**.
Both **@swc/cli** and **@swc/core** were installed as development dependencies, but the following error is being output.
For reference, there is no problem in my Windows 11 local environment.
![image](https://github.com/user-attachments/assets/88b4569f-d725-4f07-9aee-8db174f59342)

my **package.json**
![image](https://github.com/user-attachments/assets/300c8be4-3401-40ff-b689-9f5f3ca4c844)

my **nest-cli.json**
![image](https://github.com/user-attachments/assets/ad28e025-0b63-4df2-a366-a7649003ad52)

**Comment by kdy1** [comment]
Can you try running npm install from ubuntu?

**Comment by realtrynna** [comment]
> Can you try running npm install from ubuntu?

After npm i, the necessary dependencies were installed without problems.

**Comment by kdy1** [comment]
Then it's not an SWC bug. You should run `npm install` with appropriate npm arch/os config or force-install optional dependencies you need

**Comment by ahmed-mkacher** [comment]
Hello, beginner here.
I am trying to create a personal NestJS project template and I ran into the exact same issue.</br>
Nest CLI version: 10.4.7
pnpm version: 9.13.2
swc/cli version: 0.5.0
swc/core version: 1.9.2
OS: Win 11
Node version: 22.11.0 LTS</br>
my `nest-cli.json` file:
![image](https://github.com/user-attachments/assets/94d866dc-eb44-4921-a9bd-538aed1830c5)</br>
I have tried deleting node_modules/ and cache before using `pnpm install`. 
I even downgraded the swc/cli and core, but still I was getting the exact same error here.
I wonder if it's fixed and I am somehow breaking something.</br>
Please tell me if I need to provide anything else.
