### ISSUE TITLE
Error Failed to load "@swc/cli" and/or "@swc/core" required packages

### ISSUE THREAD

**Issue by ahmed-mkacher** [swc-project/pkgs#71]
Hello, beginner here.
I am trying to create a personal NestJS project template and I ran into the exact same issue.
I noticed that there was already a similar issue to this-on which I have commented too-that got closed #63 .</br> 
However who started it was using npm, while I am using pnpm, I wonder if that makes a difference.</br></br>

Nest CLI version: 10.4.7
pnpm version: 9.13.2
swc/cli version: 0.5.0
swc/core version: 1.9.2
OS: Win 11
Node version: 22.11.0 LTS</br></br>

my nest-cli.json file:
![image](https://github.com/user-attachments/assets/975b3c44-0a51-4837-9f9a-ad038ab3c31a)</br></br>

my package.json file:
![image](https://github.com/user-attachments/assets/78a9834e-751e-4138-92b9-d867dff10c7d)</br></br>

As you can see, the two packages are already dev deps.</br></br>

I have tried deleting node_modules/ and cache before using pnpm install.
I even downgraded the swc/cli and core, but still I was getting the exact same error here.
I wonder if it's fixed and I am somehow breaking something.</br></br>

Please tell me if I need to provide anything else.

**Comment by kdy1** [comment]
It's a bug of nest, not swc

**Comment by 3ximus** [comment]
This is not nest issue.
I'm not sure if this was your case but for me I was running `pnpm install --no-optional` which I believe don't download the optional prebuilt binaries. To solve this either run `pnpm install` which should get all the prebuilt binaries or add one of these as a "devDependency" depending on what you're building to:
```
@swc/core-darwin-arm64 1.11.24
@swc/core-darwin-x64 1.11.24
@swc/core-linux-arm-gnueabihf 1.11.24
@swc/core-linux-arm64-gnu 1.11.24
@swc/core-linux-arm64-musl 1.11.24
@swc/core-linux-x64-gnu 1.11.24
@swc/core-linux-x64-musl 1.11.24
@swc/core-win32-arm64-msvc 1.11.24
@swc/core-win32-ia32-msvc 1.11.24
@swc/core-win32-x64-msvc 1.11.24
```
If your target is for example the node-alpine docker image you should use: "@swc/core-linux-x64-musl"

**Comment by ahmed-mkacher** [comment]
@3ximus Thank you for adding this, I'll definitely try it once am back on that project again and explain how it went for me. for those who come after.
